use startersql;
--  select * from users where date_of_birth<'1995-09- 09';
 select *from users where date_of_birth is not null;     
--   select *from users where gender= 'female'And salary > 60000;
--  select *from users where gender= 'male'or salary > 65000;
-- select *from users where gender= 'female'And salary > 60000 order by date_of_birth desc limit 5;
-- select *from users where email is not null;
-- alter table users modify column date_of_birth datetime after salary ;
alter table users modify column name varchar(100) after id;
select * from users;